[package]
name = "base-nitro-kms"
version = "0.1.0"
authors = ["Josh Doman <joshsdoman@gmail.com>"]
edition = "2018"

[dependencies]
clap = "3.2"
log = "0.4"
nix = "0.20"
byteorder = "1.3"

[workspace]
