# Copyright 2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

FROM alpine:latest
COPY base-nitro-kms .
CMD ["./base-nitro-kms", "client", "--cid", "3",  "--port", "5005"]

